title = "Update item settings"
method = "patch"
path = "/api/v0/content/{ulid}/settings"
description = "Update the settings of a content item."
path_params = [{ name = "ulid", desc = "The ID of the content item" }]
body_params = [
    { name = "content", desc = """
The metadata for the content item. All fields are optional.

- `name`: User-facing name of the content item.
- `slug`: Custom URL path. Must be unique and contain only letters, numbers, and hyphens.
- `entrypoint`: File to start the service or task (e.g., `app.R`).
- `access_type`: One of `external`, `internal`, or `private`.
- `content_type`: The content type of the deployed item. See [documentation](/overview) for supported content types.
- `summary`: A short description of the content item.
- `tags`: An array of tags (e.g., `[\"r\", \"demo\"]`).
""" },

    { name = "serve", desc = """
Settings for service scaling and connection behavior. All fields are optional.

- `min_instances`: Minimum number of instances to keep running.
- `max_instances`: Maximum number of instances allowed.
- `spawn_threshold`: Percentage of connection load before spawning a new instance.
- `max_connections`: Max connections per instance before triggering spawn logic.
- `max_connection_age`: Time in seconds a connection can stay open.
""" },

    { name = "static", desc = """
Static site configuration. All fields are optional.

- `index`: The root file to serve (e.g., `index.html`).
- `output_dir`: Directory path where the static site output lives (e.g., `dist/`).
""" },
]

response = """
Returns the updated `_ricochet.toml` file associated with the deployed content item.
"""

[examples]
r = """
library(ricochet)
update_settings(
  "01JV7KJPREMT1JKC1PBNF0GGVP",
  content = list(
    name = "New content name",
    slug = "my-new-slug"
  )
)
"""

curl = """
curl -X PATCH https://ricochet.rs/api/v0/content/01ARZ3NDEKTSV4RRFFQ69G5FAV/settings \
    -H "Authorization: Key YOUR_API_KEY" \
    -H "Content-Type: application/json" \
    -d '{
    "content": {
        "name": "New App Name",
        "slug": "new-app-name",
        "entrypoint": "app.R",
        "access_type": "public",
        "content_type": "shiny",
        "summary": "A brief description of the app",
        "tags": ["demo", "shiny"]
    },
    "serve": {
        "min_instances": 1,
        "max_instances": 5,
        "spawn_threshold": 50,
        "max_connections": 100,
        "max_connection_age": 3600,
    },
    "static": {
        "index": "index.html",
        "output_dir": "dist/"
    }
    }'
"""
