title = "Deploy an item"
method = "post"
path = "/api/v0/content/upload"

desc = """
Deploy an R or Julia content item to Ricochet as a service or task.

To create a new content item, both a `bundle` and a `config` file must be included. The `config` field corresponds to the `_ricochet.toml` file that defines how the content should be deployed. When deploying to an existing item, the `id` must be specified, and the `config` field—if present—is ignored.

This endpoint accepts a `multipart` request and requires an API key with the `content:deploy` scope. Returns the `id` of the content item and the `deployment_id` of the new deployment.
"""

body_params = [
    { name = "bundle", desc = "A compressed `.tar.gz` archive of the content. Must be included with `Content-Type: application/x-tar`." },
    { name = "config", desc = "The `_ricochet.toml` file describing the content item. Must be included with `Content-Type: application/toml`. Required when creating a new item; ignored if `id` is specified." },
    { name = "id", desc = "The ID of an existing content item. If provided, a new deployment is created for this item." },
]

[examples]
curl = """
# deploy a new item
curl -X POST https://dev.ricochet.rs/api/v0/content/upload \
  -H "Authorization: Key YOUR_API_KEY" \
  -F "bundle=@bundle.tar.gz;type=application/x-tar" \
  -F "config=@_ricochet.toml;type=application/toml"

# deploy an existing item
curl -X POST https://dev.ricochet.rs/api/v0/content/upload \
  -H "Authorization: Key YOUR_API_KEY" \
  -F "bundle=@bundle.tar.gz;type=application/x-tar" \
  -F "id=existing-content-id"
"""

r = """
library(ricochet)
deploy("path/to/project")
"""
