when:
  - event: [pull_request, pull_request_closed]
  - event: manual
  - event: push
    branch: ${CI_REPO_DEFAULT_BRANCH}

labels:
  type: static

depends_on:
  - lint

steps:
  - name: Build
    image: oven/bun:1.2
    commands:
      - bun install
      - bunx --bun astro build

  - name: PR docs preview
    image: codeberg.org/woodpecker-plugins/plugin-surge-preview:1.4.0
    settings:
      path: "./dist"
      surge_token:
        from_secret: surge_token
      forge_repo_token:
        from_secret: ricochet_issue_token
      forge_type: github
    when:
      - event: [pull_request, pull_request_closed]

  - name: "Upload to S3"
    image: reg.ricochet.rs/docker.io/woodpeckerci/plugin-s3:1.5.2
    settings:
      bucket: ricochet-docs
      region: fsn1
      endpoint: https://fsn1.your-objectstorage.com
      access_key:
        from_secret: s3_access_key
      secret_key:
        from_secret: s3_secret_key
      source: dist/**/*
      strip_prefix: dist/
      overwrite: true
      retry_count: 3
      path_style: true
    when:
      - event: manual
      - event: push
        branch: ${CI_REPO_DEFAULT_BRANCH}
