title = "Stop an active invocation"
method = "post"
path = "/api/v0/content/{ulid}/invocations/{id}/stop"
description = "Schedules a task to run on a recurring schedule. Tasks are schedule using cron syntax. See the [scheduling content](/scheduling) documentation for more on the supported cron syntax."
path_params = [
    { name = "ulid", desc = "The ID of the content item" },
    { name = "id", desc = "The ID of the invocation" },
]
response = """
Returns a json object with the field `success` which contains either `true` or `false`.
"""

[examples]
r = """
```r
library(ricochet)
stop_invocation(
  "01ARZ3NDEKTSV4RRFFQ69G5FAV",
  "01JY9N5GNVN7GMZB88D9FTPNKA"
)
```
"""

curl = """
```bash
curl -X POST https://ricochet.rs/api/v0/content/01ARZ3NDEKTSV4RRFFQ69G5FAV/invocations/01JY9N5GNVN7GMZB88D9FTPNKA/stop \\
    -H "Authorization: Key YOUR_API_KEY"
```
"""
