name: Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: extractions/setup-just@v3
      - uses: moonrepo/setup-rust@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          components: rustfmt
          bins: leptosfmt
      - name: Check formatting
        run: |
          cargo fmt --all --check
          leptosfmt --check ricochet-ui/src/**/*.rs
          leptosfmt --check ricochet-ui/src/*.rs
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: moonrepo/setup-rust@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          components: clippy

      - uses: extractions/setup-just@v3
      - name: Run linter
        run: just lint
